version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.6.2
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: run --enable-api --cors "*" --debug
    depends_on:
      - action-server

  action-server:
    build: .
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: start --actions actions.actions 